// <auto-generated />
namespace Magni.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateddates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddates));
        
        string IMigrationMetadata.Id
        {
            get { return "202205031433056_updated dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
